### ISSUE TITLE
How can I  create collectionID in AWS

### ISSUE THREAD

**Issue by KalyanMohanty** [Arbazkhan4712/Face-Recognition-Door-Lock-with-AWS-Rekognition-Raspberry-Pi3#1]
Hi Arbaz, How can I  create collectionID in AWS. I have completed all necessary steps in aws. And also can you share me idea how to do it in opencv using my own camera?

**Comment by Arbazkhan4712** [comment]
you can give any name to collection id it is not required to create any collection on the AWS side just add some random name in the program so it will automatically create a collection .
If you are planning to use OpenCV then also keep in mind that it will be very CPU intensive and not that much accurate.
You can train a harr cascade file with your images to detect using OpenCV

**Comment by KalyanMohanty** [comment]
Thank you Arbaz.
